[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
libobs-recorder = { git = "https://github.com/FFFFFFFXXXXXXX/libobs-recorder", features = ["types-only", "serde"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
