// This file has been generated by Specta. DO NOT EDIT.

export type GameInfo = { gameMode: string; summonerName: string; championName: string }

export type RateControl = { CBR: number } | { VBR: number } | { CQP: number } | { CRF: number } | { ICQ: number }

export type Encoder = "JIM_NVENC" | "FFMPEG_NVENC" | "JIM_AV1" | "AMD_AMF_H264" | "AMD_AMF_AV1" | "OBS_QSV11_H264" | "OBS_QSV11_AV1" | "OBS_X264"

/**
 * most common resolutions for the aspect ratios 4:3, 5:4, 16:9, 16:10, 21:9, 43:18, 24:10, 32:9, 32:10
 */
export type Resolution = "1024x768p" | "1600x1200p" | "1280x1024p" | "1280x720p" | "1366x768p" | "1600x900p" | "1920x1080p" | "2560x1440p" | "3840x2160p" | "5120x2880p" | "1280x800p" | "1440x900p" | "1680x1050p" | "1920x1200p" | "2240x1400p" | "2560x1600p" | "2560x1080p" | "5120x2160p" | "2580x1080p" | "3440x1440p" | "3840x1600p" | "3840x1080p" | "5120x1440p" | "3840x1200p"

export type RecorderSettings = { window: Window | null; input_resolution: Size | null; output_resolution: Size | null; framerate: Framerate | null; rate_control: RateControl | null; record_audio: AudioSource | null; output_path: string | null; encoder: Encoder | null }

export type MarkerFlags = { kill: boolean; death: boolean; assist: boolean; turret: boolean; inhibitor: boolean; dragon: boolean; herald: boolean; baron: boolean }

export type Window = { name: string; class: string | null; process: string | null }

export type GameEvent = { name: EventName; time: number }

export type Settings = { markerFlags: MarkerFlags; checkForUpdates: boolean; debugLog: boolean; recordingsFolder: string; filenameFormat: string; encodingQuality: number; outputResolution?: Resolution | null; framerate: Framerate; recordAudio: AudioSource; autostart: boolean }

export type GameData = { win: boolean | null; gameInfo: GameInfo; stats: Stats; events: GameEvent[] }

export type EventName = "Kill" | "Death" | "Assist" | "Voidgrub" | "Herald" | "Baron" | "Inhibitor" | "Turret" | "InfernalDragon" | "OceanDragon" | "MountainDragon" | "CloudDragon" | "HextechDragon" | "ChemtechDragon" | "ElderDragon"

export type Stats = { kills: number; deaths: number; assists: number; minionsKilled?: number; neutralMinionsKilled?: number; wardScore?: number }

export type Size = { width: number; height: number }

export type AudioSource = "NONE" | "APPLICATION" | "SYSTEM" | "ALL"

export type Framerate = [number, number]

