/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function showAppWindow() {
    return invoke()<null>("show_app_window")
}

export function getMarkerFlags() {
    return invoke()<MarkerFlags>("get_marker_flags")
}

export function setMarkerFlags(markerFlags: MarkerFlags) {
    return invoke()<null>("set_marker_flags", { markerFlags })
}

export function getAssetPort() {
    return invoke()<number>("get_asset_port")
}

export function getRecordingsSize() {
    return invoke()<number>("get_recordings_size")
}

export function getRecordingsList() {
    return invoke()<string[]>("get_recordings_list")
}

export function openRecordingsFolder() {
    return invoke()<null>("open_recordings_folder")
}

export function deleteVideo(videoId: string) {
    return invoke()<boolean>("delete_video", { videoId })
}

export function renameVideo(videoId: string, newVideoId: string) {
    return invoke()<boolean>("rename_video", { videoId,newVideoId })
}

export function getMetadata(videoId: string) {
    return invoke()<GameData | null>("get_metadata", { videoId })
}

export type GameData = { win: boolean | null; gameInfo: GameInfo; stats: Stats; events: GameEvent[] }
export type GameEvent = { name: EventName; time: number }
export type EventName = "Kill" | "Death" | "Assist" | "Voidgrub" | "Herald" | "Baron" | "Inhibitor" | "Turret" | "InfernalDragon" | "OceanDragon" | "MountainDragon" | "CloudDragon" | "HextechDragon" | "ChemtechDragon" | "ElderDragon"
export type GameInfo = { gameMode: string; summonerName: string; championName: string }
export type MarkerFlags = { kill: boolean; death: boolean; assist: boolean; turret: boolean; inhibitor: boolean; dragon: boolean; herald: boolean; baron: boolean }
export type Stats = { kills: number; deaths: number; assists: number; minionsKilled?: number; neutralMinionsKilled?: number; wardScore?: number }
